### ISSUE TITLE
starting as a cron job?

### ISSUE THREAD

**Issue by mgaulton** [Lex-2008/facebook2email#2]
Trying to build a way to recover as a service. Doesn't seem to wait the way I'm expecting for the driver load and since I'm basing it on your code, do you have any suggestions?

```
#!/bin/bash

IMAGE_NAME="ultrafunk/undetected-chromedriver"

# Find running containers matching the image name
CONTAINERS=$(docker ps -a --format '{{.ID}} {{.Image}}' | grep $IMAGE_NAME | awk '{print $1}')

if [ -z "$CONTAINERS" ]; then
    echo "No running containers found for $IMAGE_NAME"
else
    echo "Stopping running containers for $IMAGE_NAME..."
    # Stop each container one by one
    for CONTAINER in $CONTAINERS; do
        docker stop $CONTAINER
        echo "Container $CONTAINER stopped."
    done
fi

docker run --rm -d -v /opt/brgc/facebook2email:/data -p 5900:5900 --shm-size=2g ultrafunk/undetected-chromedriver bash -c 'x11vnc >x11vnc.log 2>&1 & sleep 5 && python -c "import undetected_chromedriver as uc; driver = uc.Chrome(advanced_elements=True, user_data_dir='/data/profile')" && sleep 5'

docker run --rm -v /opt/brgc/facebook2email:/data --shm-size=2g ultrafunk/undetected-chromedriver /data/scriptmg2.py
#>last.log 2>&1
```

**Comment by Lex-2008** [comment]
hmm...

first, if you need/want to find the container afterwards, you can just add name to it: add `--name=facebook2email` to the `docker run` command and then use
```
CONTAINER="$(docker ps -qf name=facebook2email)"
```
to find it.

As a bonus(?), you won't be able to start two containers with same name.

Also, I don't really understand why do you want to have two `docker run` commands in your cron file. First starts VNC server, and exits 5 seconds after? :) Or is it just for testing?

The reason why it doesn't work as expected, I believe, is because first `docker run` command has `-d` argument - it makes docker "detach" - i.e. spawn the container in background and continue to the next line in the bash script.

Also note that Chrome really doesn't like having two browsers running with the same profile at the same time, so you shouldn't have two docker containers running in parallel like this. If you want to have Python script running **and** a possibility  to connect VNC to it (to see what's going on), you should do it in a single container, like this:

```
docker run --rm -v /opt/brgc/facebook2email:/data -p 5900:5900 --shm-size=2g ultrafunk/undetected-chromedriver bash -c 'x11vnc >x11vnc.log 2>&1 & /data/script.py'
```

**Comment by mgaulton** [comment]
just for testing on the 2nd command. I want to restart the docker if failed. Running the process in corn.
vnc Is secondary really. As long as chromedriver is starting and I can run the script, that's all i need. 
I missed the -d on the docker line, that makes sense.

**Comment by mgaulton** [comment]
For some reason, I was thinking I had to manually init the chrome driver in the container before I could later run the script. so 
stage 1 was run x11vnc and init the driver
stage 2 run the actual script.
